name: PHP Code Standard

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP Syntax
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Coding Standard Check
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          ~/.composer/vendor/bin/phpcs --standard=PSR12 .
